name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**/*.sh'
      - '**/*.conf'
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发构建
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]  # 构建两个架构的镜像

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          # 获取当前时间年月日时分，作为自定义标签
          TIME_TAG="$(date +'%Y%m%d%H%M')"
          # 基本镜像名称
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/medialinker"

          # 构建并推送镜像，同时为所有架构使用相同标签
          docker buildx build --platform linux/${{ matrix.architecture }} \
            -t $IMAGE_NAME:${TIME_TAG} \
            -t $IMAGE_NAME:latest \
            --push .

      - name: Check for repository updates
        run: |
          git fetch --tags
          # 确保有足够的提交历史才能比较差异
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only HEAD HEAD~1
          else
            echo "No previous commit to compare."
          fi

      - name: Trigger new build on update
        if: github.event.head_commit.message != 'Merge pull request' && github.event.head_commit.message != 'Automated build'
        run: echo "Repository has been updated, building new image."
